// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsiU_9Mm9Z5qDyEwAwPbEUSeKq9wR2v6M',
    appId: '1:192975131663:web:0a5aa92281c0e7a0257f7a',
    messagingSenderId: '192975131663',
    projectId: 'classmate-f0a6d',
    authDomain: 'classmate-f0a6d.firebaseapp.com',
    storageBucket: 'classmate-f0a6d.firebasestorage.app',
    measurementId: 'G-QY97MLBZGN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7LocaTqko92sSABlISRVwkrdQbu4T3ks',
    appId: '1:192975131663:android:7f798c07f6761d99257f7a',
    messagingSenderId: '192975131663',
    projectId: 'classmate-f0a6d',
    storageBucket: 'classmate-f0a6d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeVJ11wfSbHoRq1kr0bRNUmrQpdwhq-mU',
    appId: '1:192975131663:ios:85c39400ec571076257f7a',
    messagingSenderId: '192975131663',
    projectId: 'classmate-f0a6d',
    storageBucket: 'classmate-f0a6d.firebasestorage.app',
    iosClientId: '192975131663-39eta9nf5aqiu0lbpe61n6h101kuf3vg.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeVJ11wfSbHoRq1kr0bRNUmrQpdwhq-mU',
    appId: '1:192975131663:ios:85c39400ec571076257f7a',
    messagingSenderId: '192975131663',
    projectId: 'classmate-f0a6d',
    storageBucket: 'classmate-f0a6d.firebasestorage.app',
    iosClientId: '192975131663-39eta9nf5aqiu0lbpe61n6h101kuf3vg.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsiU_9Mm9Z5qDyEwAwPbEUSeKq9wR2v6M',
    appId: '1:192975131663:web:474d05848df4a0d1257f7a',
    messagingSenderId: '192975131663',
    projectId: 'classmate-f0a6d',
    authDomain: 'classmate-f0a6d.firebaseapp.com',
    storageBucket: 'classmate-f0a6d.firebasestorage.app',
    measurementId: 'G-K8YKR8WNQ2',
  );
}
